name: Trigger auto deployment for ssheasy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ssheasy-AutoDeployTrigger-c1e6f239-b46d-465a-91d8-a71faf3a1702.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SSHEASY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SSHEASY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SSHEASY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.SSHEASY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SSHEASY_REGISTRY_PASSWORD }}
          containerAppName: ssheasy
          resourceGroup: Default-ActivityLogAlerts
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


